# Generated by Django 2.2.3 on 2019-07-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_test2_age4'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='name1',
            field=models.CharField(default='', max_length=225),
        ),
    ]
