# Generated by Django 2.2.3 on 2019-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_test2_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='age1',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='age3',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='age4',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='type1',
        ),
        migrations.AddField(
            model_name='test2',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='test2',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
    ]
