# Generated by Django 2.2.3 on 2019-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20190704_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, max_length=4, verbose_name='年龄')),
            ],
        ),
    ]
