# Generated by Django 2.2.3 on 2019-07-04 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20190704_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
